back:
  calabash:
    android: "cordovaWebView css:'.ui-btn-left'"
    ios:
  appium:
    android:
    ios:

login_page:
  calabash:
    android: "cordovaWebView css:'.ui-title' textContent:'Login'"
    ios:
  appium:
    android:
    ios:

main_page:
  calabash:
    android: "cordovaWebView css:'.ui-title' textContent:'Hi Jaxon!'"
    ios:
  appium:
    android:
    ios:

my_trips_page:
  calabash:
    android: "cordovaWebView css:'.ui-title' textContent:'My Trips'" 
    ios:
  appium:
    android:
    ios:

flight_status_page:
  calabash:
    android: "cordovaWebView css:'.ui-title' textContent:'Flight Status'"
    ios:
  appium:
    android:
    ios:

track_your_bag_page:
  calabash:
    android: "cordovaWebView css:'.ui-title' textContent:'Bag Track'"
    ios:
  appium:
    android:
    ios:

mileage_program_progress_page:
  calabash:
    android: "cordovaWebView css:'.ui-title' textContent:'Progress'"
    ios:
  appium:
    android:
    ios:

settings_page:
  calabash:
    android: "cordovaWebView css:'.ui-title' textContent:'Settings'"
    ios:
  appium:
    android:
    ios:

