user:
  calabash:
    android: "cordovaWebView css:'#userName'"
    ios: ""
  appium:
    android: "org.wordpress.android:id/userName"
    ios: ""

pass:
  calabash:
    android: "org.apache.cordova.CordovaWebView css:'#pwd'"
    ios: ""
  appium:
    android: "org.wordpress.android:id/pwd"
    ios: ""

sign_in:
  calabash:
    android: "org.apache.cordova.CordovaWebView css:'.ui-btn-hidden'"
    ios: ""
  appium:
    android: "org.apache.cordova.CordovaWebView css:'.ui-btn-hidden'"
    ios: ""
